"""
Agent Context Protocol: Converts agent-generated actions into system behaviors.

This module is responsible for:
1. Parsing agent-generated actions (from LLM responses)
2. Converting them into system API calls based on experiment type
3. Executing these actions through the appropriate routes/handlers

The system supports customizable action handlers for different experiment types.
"""

import json
import uuid
from typing import Dict, List, Any, Optional, Callable
from datetime import datetime
import routes.session as session_module
from routes.participant import find_session_by_identifier, get_value_from_session_params
from websocket.handlers import broadcast_participant_update, get_socketio
from functions import start_production


# Global registry for action handlers by experiment type
_action_handlers: Dict[str, Dict[str, Callable]] = {}


def register_action_handler(experiment_type: str, action_type: str, handler: Callable):
    """
    Register an action handler for a specific experiment type.
    
    Args:
        experiment_type: The experiment type (e.g., 'shapefactory', 'daytrader')
        action_type: The action type (e.g., 'produce_shape', 'make_investment')
        handler: The handler function that takes (self, action, participant, session, session_key) and returns a result dict
    """
    if experiment_type not in _action_handlers:
        _action_handlers[experiment_type] = {}
    _action_handlers[experiment_type][action_type] = handler


def get_action_handler(experiment_type: str, action_type: str) -> Optional[Callable]:
    """Get action handler for a specific experiment type and action type"""
    return _action_handlers.get(experiment_type, {}).get(action_type)


class AgentContextProtocol:
    """Protocol for converting agent actions to system behaviors"""
    
    def __init__(self, participant_id: str, session_id: str, experiment_type: str):
        """
        Initialize the protocol for a specific agent participant.
        
        Args:
            participant_id: The ID of the agent participant
            session_id: The ID of the session
            experiment_type: The experiment type (e.g., 'shapefactory', 'daytrader')
        """
        self.participant_id = participant_id
        self.session_id = session_id
        self.experiment_type = experiment_type
        self.sessions = session_module.sessions
    
    def execute_actions(self, actions: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Execute a list of actions generated by the agent.
        
        Args:
            actions: List of action dictionaries from agent response
        
        Returns:
            Dict with execution results, including successes and failures
        """
        results = {
            'successful': [],
            'failed': [],
            'errors': []
        }
        
        # Find session
        session_key, session = self._find_session()
        if not session:
            return {
                'error': 'Session not found',
                **results
            }
        
        # Find participant
        participant = self._find_participant(session)
        if not participant:
            return {
                'error': 'Participant not found',
                **results
            }
        
        # Execute each action
        for action in actions:
            if not isinstance(action, dict):
                results['failed'].append({
                    'action': action,
                    'error': 'Invalid action format'
                })
                continue
            
            action_type = action.get('type')
            if not action_type:
                results['failed'].append({
                    'action': action,
                    'error': 'Missing action type'
                })
                continue
            
            try:
                result = self._execute_single_action(action, participant, session, session_key)
                if result.get('success'):
                    results['successful'].append(result)
                    # Log agent action
                    self._log_agent_action(action, action_type, result, participant, session, session_key)
                else:
                    results['failed'].append(result)
            except Exception as e:
                error_msg = str(e)
                results['failed'].append({
                    'action': action,
                    'error': error_msg
                })
                results['errors'].append(error_msg)
        
        return results
    
    def _execute_single_action(
        self, 
        action: Dict[str, Any], 
        participant: Dict[str, Any],
        session: Dict[str, Any],
        session_key: str
    ) -> Dict[str, Any]:
        """
        Execute a single action.
        
        Args:
            action: Action dictionary
            participant: Participant object
            session: Session object
            session_key: Session key in storage
        
        Returns:
            Dict with success status and result/error
        """
        action_type = action.get('type')
        
        # Try to get experiment-specific handler first
        handler = get_action_handler(self.experiment_type, action_type)
        if handler:
            return handler(self, action, participant, session, session_key)
        
        # Fall back to common handlers
        if action_type == 'message':
            return self._execute_message(action, participant, session, session_key)
        else:
            return {
                'success': False,
                'action': action,
                'error': f'Unknown action type: {action_type} for experiment {self.experiment_type}'
            }
    
    def _execute_message(
        self, 
        action: Dict[str, Any],
        participant: Dict[str, Any],
        session: Dict[str, Any],
        session_key: str
    ) -> Dict[str, Any]:
        """Execute send_message action (common across all experiments)"""
        recipient_code = action.get('recipient')
        content = action.get('content', '').strip()
        
        if not recipient_code:
            return {
                'success': False,
                'action': action,
                'error': 'Missing recipient'
            }
        
        if not content:
            return {
                'success': False,
                'action': action,
                'error': 'Message content cannot be empty'
            }
        
        # Check if this is a group chat message (recipient is "all")
        participants = session.get('participants', [])
        is_group_chat = recipient_code.lower() == 'all'
        
        recipient = None
        if not is_group_chat:
            # Find recipient participant by name/code
            for p in participants:
                p_name = p.get('name') or p.get('participant_name')
                if p_name and p_name.lower() == recipient_code.lower():
                    recipient = p
                    break
            
            if not recipient:
                return {
                    'success': False,
                    'action': action,
                    'error': f'Recipient not found: {recipient_code}'
                }
        
        # Create message object
        message = {
            'id': str(uuid.uuid4()),
            'session_id': self.session_id,
            'sender': self.participant_id,
            'receiver': None if is_group_chat else recipient.get('id'),  # None for group chat
            'content': content,
            'timestamp': datetime.now().isoformat()
        }
        
        # Store message in session
        if 'messages' not in session:
            session['messages'] = []
        session['messages'].append(message)
        
        # Store in participants' message history
        # For group chat, store for all participants; for private chat, store for sender and recipient
        for p in participants:
            p_id = p.get('id') or p.get('participant_id')
            if is_group_chat or p_id == self.participant_id or (recipient and p_id == recipient.get('id')):
                if 'messages' not in p:
                    p['messages'] = []
                p['messages'].append(message)
        
        # Update session storage
        self.sessions[session_key] = session
        
        # Broadcast message via WebSocket
        socketio = get_socketio()
        socketio.emit('message_received', message, room=self.session_id)
        
        return {
            'success': True,
            'action': action,
            'message_id': message['id']
        }
    
    def _find_session(self):
        """Find session by session_id"""
        return find_session_by_identifier(self.session_id)
    
    def _find_participant(self, session: Dict[str, Any]):
        """Find participant by participant_id"""
        participants = session.get('participants', [])
        for p in participants:
            if p.get('id') == self.participant_id:
                return p
        return None

    def _log_agent_action(
        self,
        action: Dict[str, Any],
        action_type: str,
        result: Dict[str, Any],
        participant: Dict[str, Any],
        session: Dict[str, Any],
        session_key: str,
    ):
        """Log agent action with session_status (public + private)."""
        action_content = self._format_action_content(action, action_type, result)
        actual_session_id = session.get('session_id') or session_key
        from services.action_logger import log_action
        log_action(
            session_id=actual_session_id,
            participant_id=self.participant_id,
            is_human=False,
            action_type=action_type,
            action_content=action_content,
            result='success',
            metadata={k: v for k, v in (result or {}).items() if k not in ('success', 'action')},
            experiment_type=self.experiment_type,
            session=session,
            participant=participant,
        )

    def _format_action_content(self, action: Dict[str, Any], action_type: str, result: Dict[str, Any]) -> str:
        """Format action content for logging."""
        if action_type == 'message':
            return (action.get('content') or '')[:200]
        if action_type == 'propose_trade_offer':
            target = action.get('target_participant', '')
            shape = action.get('shape', '')
            price = action.get('price_per_unit', '')
            offer_type = action.get('offer_type', '')
            return f"{offer_type} {shape} to {target} @ ${price}"
        if action_type == 'trade_response':
            return f"{action.get('response_type', '')} {action.get('transaction_id', '')}"
        if action_type in ('accept_trade_offer', 'decline_trade_offer'):
            return f"{action_type}: {result.get('offer_id', action.get('transaction_id', ''))}"
        if action_type == 'cancel_trade_offer':
            return f"cancel {action.get('transaction_id', '')}"
        if action_type in ('submit_initial_vote', 'submit_final_vote'):
            return str(action.get('selected', action.get('candidate', '')))
        if action_type == 'make_investment':
            return f"${action.get('amount', '')} ({action.get('investment_type', '')})"
        if action_type == 'produce_shape':
            return str(action.get('shape', ''))
        return str(action)[:200]


# ============================================================================
# ShapeFactory-specific action handlers
# ============================================================================

def _execute_propose_trade_offer_shapefactory(
    self: AgentContextProtocol,
    action: Dict[str, Any],
    participant: Dict[str, Any],
    session: Dict[str, Any],
    session_key: str
) -> Dict[str, Any]:
    """Execute propose_trade_offer action for ShapeFactory"""
    offer_type = action.get('offer_type')  # 'buy' or 'sell'
    shape = action.get('shape')
    price_per_unit = action.get('price_per_unit')
    target_participant_code = action.get('target_participant')
    
    if offer_type not in ['buy', 'sell']:
        return {
            'success': False,
            'action': action,
            'error': f'Invalid offer_type: {offer_type}'
        }
    
    if not shape:
        return {
            'success': False,
            'action': action,
            'error': 'Missing shape'
        }
    
    if price_per_unit is None:
        return {
            'success': False,
            'action': action,
            'error': 'Missing price_per_unit'
        }
    
    try:
        price = float(price_per_unit)
    except (ValueError, TypeError):
        return {
            'success': False,
            'action': action,
            'error': f'Invalid price_per_unit: {price_per_unit}'
        }
    
    if not target_participant_code:
        return {
            'success': False,
            'action': action,
            'error': 'Missing target_participant'
        }
    
    # Find target participant by name/code
    participants = session.get('participants', [])
    target_participant = None
    for p in participants:
        p_name = p.get('name') or p.get('participant_name')
        if p_name and p_name.lower() == target_participant_code.lower():
            target_participant = p
            break
    
    if not target_participant:
        return {
            'success': False,
            'action': action,
            'error': f'Target participant not found: {target_participant_code}'
        }
    
    # Validate trade constraints
    if offer_type == 'sell':
        # Check if seller has the shape in inventory
        exp_params = participant.get('experiment_params', {})
        inventory = exp_params.get('inventory', [])
        if shape not in inventory:
            return {
                'success': False,
                'action': action,
                'error': f'You do not have {shape} in your inventory'
            }
        
        # Check if buyer has enough money
        target_exp_params = target_participant.get('experiment_params', {})
        buyer_money = target_exp_params.get('money', 0)
        if buyer_money < price:
            return {
                'success': False,
                'action': action,
                'error': 'Buyer does not have enough money'
            }
    elif offer_type == 'buy':
        # Check if buyer has enough money
        exp_params = participant.get('experiment_params', {})
        buyer_money = exp_params.get('money', 0)
        if buyer_money < price:
            return {
                'success': False,
                'action': action,
                'error': 'You do not have enough money'
            }
    
    # Create trade offer
    if 'pending_offers' not in session:
        session['pending_offers'] = []
    
    offer_id = str(uuid.uuid4())
    offer = {
        'id': offer_id,
        'from': self.participant_id,
        'to': target_participant.get('id'),
        'offer_type': offer_type,
        'item_type': 'shape',
        'quantity': 1,
        'price': price,
        'status': 'pending',
        'timestamp': datetime.now().isoformat(),
        'trade_item': shape,
        'shape': shape  # Backward compatibility
    }
    
    session['pending_offers'].append(offer)
    self.sessions[session_key] = session
    
    # Broadcast update
    broadcast_participant_update(
        session_id=self.session_id,
        participants=participants,
        session_info=session,
        update_type='trade_update'
    )
    
    return {
        'success': True,
        'action': action,
        'offer_id': offer_id
    }


def _execute_cancel_trade_offer_shapefactory(
    self: AgentContextProtocol,
    action: Dict[str, Any],
    participant: Dict[str, Any],
    session: Dict[str, Any],
    session_key: str
) -> Dict[str, Any]:
    """Execute cancel_trade_offer action for ShapeFactory"""
    transaction_id = action.get('transaction_id')
    
    if not transaction_id:
        return {
            'success': False,
            'action': action,
            'error': 'Missing transaction_id'
        }
    
    pending_offers = session.get('pending_offers', [])
    offer = None
    offer_index = None
    
    for i, o in enumerate(pending_offers):
        if o.get('id') == transaction_id:
            offer = o
            offer_index = i
            break
    
    if not offer:
        return {
            'success': False,
            'action': action,
            'error': f'Offer not found: {transaction_id}'
        }
    
    if offer.get('from') != self.participant_id:
        return {
            'success': False,
            'action': action,
            'error': 'You are not the sender of this offer'
        }
    
    if offer.get('status') != 'pending':
        return {
            'success': False,
            'action': action,
            'error': 'Offer is no longer pending'
        }
    
    # Create cancelled trade record
    if 'completed_trades' not in session:
        session['completed_trades'] = []
    
    cancelled_trade = {
        'id': str(uuid.uuid4()),
        'from': offer.get('from'),
        'to': offer.get('to'),
        'offer_type': offer.get('offer_type'),
        'item_type': offer.get('item_type', 'shape'),
        'quantity': offer.get('quantity', 1),
        'price': offer.get('price'),
        'status': 'cancelled',
        'timestamp': datetime.now().isoformat()
    }
    
    trade_item = offer.get('trade_item') or offer.get('shape')
    if trade_item:
        cancelled_trade['trade_item'] = trade_item
        if offer.get('item_type', 'shape') == 'shape':
            cancelled_trade['shape'] = trade_item
    
    session['completed_trades'].append(cancelled_trade)
    
    # Remove from pending offers
    pending_offers.pop(offer_index)
    offer['status'] = 'cancelled'
    session['pending_offers'] = pending_offers
    self.sessions[session_key] = session
    
    # Broadcast update
    participants = session.get('participants', [])
    broadcast_participant_update(
        session_id=self.session_id,
        participants=participants,
        session_info=session,
        update_type='trade_update'
    )
    
    return {
        'success': True,
        'action': action,
        'offer_id': transaction_id
    }


def _execute_trade_response_shapefactory(
    self: AgentContextProtocol,
    action: Dict[str, Any],
    participant: Dict[str, Any],
    session: Dict[str, Any],
    session_key: str
) -> Dict[str, Any]:
    """Execute trade_response action (accept/decline) for ShapeFactory"""
    transaction_id = action.get('transaction_id')
    response_type = action.get('response_type')  # 'accept' or 'decline'
    
    if not transaction_id:
        return {
            'success': False,
            'action': action,
            'error': 'Missing transaction_id'
        }
    
    if response_type not in ['accept', 'decline']:
        return {
            'success': False,
            'action': action,
            'error': f'Invalid response_type: {response_type}'
        }
    
    pending_offers = session.get('pending_offers', [])
    offer = None
    offer_index = None
    
    for i, o in enumerate(pending_offers):
        if o.get('id') == transaction_id:
            offer = o
            offer_index = i
            break
    
    if not offer:
        return {
            'success': False,
            'action': action,
            'error': f'Offer not found: {transaction_id}'
        }
    
    if offer.get('to') != self.participant_id:
        return {
            'success': False,
            'action': action,
            'error': 'You are not the recipient of this offer'
        }
    
    if offer.get('status') != 'pending':
        return {
            'success': False,
            'action': action,
            'error': 'Offer is no longer pending'
        }
    
    participants = session.get('participants', [])
    from_participant = None
    to_participant = participant
    
    for p in participants:
        if p.get('id') == offer.get('from'):
            from_participant = p
            break
    
    if not from_participant:
        return {
            'success': False,
            'action': action,
            'error': 'Sender participant not found'
        }
    
    if response_type == 'accept':
        # Execute the trade (same logic as in participant.py)
        trade_item = offer.get('trade_item') or offer.get('shape')
        item_type = offer.get('item_type', 'shape')
        quantity = offer.get('quantity', 1)
        price = offer.get('price')
        offer_type = offer.get('offer_type')
        
        from_exp_params = from_participant.get('experiment_params', {})
        to_exp_params = to_participant.get('experiment_params', {})
        
        # Validate seller has item
        if trade_item and item_type != 'price_only':
            seller_inventory = None
            if offer_type == 'sell':
                seller_inventory = from_exp_params.get('inventory', [])
            elif offer_type == 'buy':
                seller_inventory = to_exp_params.get('inventory', [])
            
            if seller_inventory is not None:
                if item_type == 'shape':
                    item_count = seller_inventory.count(trade_item)
                    if item_count < quantity:
                        return {
                            'success': False,
                            'action': action,
                            'error': f'Seller does not have {quantity}x {trade_item} in inventory'
                        }
        
        # Validate buyer has money
        buyer_money = None
        if offer_type == 'sell':
            buyer_money = to_exp_params.get('money', 0)
        elif offer_type == 'buy':
            buyer_money = from_exp_params.get('money', 0)
        
        if buyer_money is not None and buyer_money < price:
            return {
                'success': False,
                'action': action,
                'error': f'Buyer does not have enough money (has ${buyer_money}, needs ${price})'
            }
        
        # Execute trade
        def remove_item_from_inventory(inventory, item, item_type, qty=1):
            if not isinstance(inventory, list):
                return inventory
            new_inventory = inventory.copy()
            for _ in range(qty):
                if item_type == 'shape':
                    if item in new_inventory:
                        new_inventory.remove(item)
                else:
                    for i, inv_item in enumerate(new_inventory):
                        if isinstance(inv_item, dict):
                            if inv_item.get('type') == item_type and inv_item.get('value') == item:
                                new_inventory.pop(i)
                                break
                        elif inv_item == item:
                            new_inventory.pop(i)
                            break
            return new_inventory
        
        def add_item_to_inventory(inventory, item, item_type, qty=1):
            if not isinstance(inventory, list):
                inventory = []
            new_inventory = inventory.copy()
            for _ in range(qty):
                if item_type == 'shape':
                    new_inventory.append(item)
                else:
                    new_inventory.append({'type': item_type, 'value': item})
            return new_inventory
        
        if offer_type == 'sell':
            if trade_item and item_type != 'price_only':
                from_inventory = from_exp_params.get('inventory', [])
                from_exp_params['inventory'] = remove_item_from_inventory(from_inventory, trade_item, item_type, quantity)
                
                to_inventory = to_exp_params.get('inventory', [])
                to_exp_params['inventory'] = add_item_to_inventory(to_inventory, trade_item, item_type, quantity)
            
            from_money = from_exp_params.get('money', 0)
            from_exp_params['money'] = from_money + price
            
            to_money = to_exp_params.get('money', 0)
            to_exp_params['money'] = to_money - price
            
        elif offer_type == 'buy':
            if trade_item and item_type != 'price_only':
                to_inventory = to_exp_params.get('inventory', [])
                to_exp_params['inventory'] = remove_item_from_inventory(to_inventory, trade_item, item_type, quantity)
                
                from_inventory = from_exp_params.get('inventory', [])
                from_exp_params['inventory'] = add_item_to_inventory(from_inventory, trade_item, item_type, quantity)
            
            to_money = to_exp_params.get('money', 0)
            to_exp_params['money'] = to_money + price
            
            from_money = from_exp_params.get('money', 0)
            from_exp_params['money'] = from_money - price
        
        from_participant['experiment_params'] = from_exp_params
        to_participant['experiment_params'] = to_exp_params
        
        # Recompute interfaces
        from routes.participant import update_participant_experiment_params
        update_participant_experiment_params(from_participant, session)
        update_participant_experiment_params(to_participant, session)
        
        # Create completed trade record
        if 'completed_trades' not in session:
            session['completed_trades'] = []
        
        completed_trade = {
            'id': str(uuid.uuid4()),
            'from': offer.get('from'),
            'to': offer.get('to'),
            'offer_type': offer_type,
            'item_type': item_type,
            'quantity': quantity,
            'price': price,
            'status': 'completed',
            'timestamp': datetime.now().isoformat()
        }
        
        if trade_item:
            completed_trade['trade_item'] = trade_item
            if item_type == 'shape':
                completed_trade['shape'] = trade_item
        
        session['completed_trades'].append(completed_trade)
        
        # Remove from pending offers
        pending_offers.pop(offer_index)
        offer['status'] = 'accepted'
    else:  # decline
        # Create declined trade record
        if 'completed_trades' not in session:
            session['completed_trades'] = []
        
        declined_trade = {
            'id': str(uuid.uuid4()),
            'from': offer.get('from'),
            'to': offer.get('to'),
            'offer_type': offer.get('offer_type'),
            'item_type': offer.get('item_type', 'shape'),
            'quantity': offer.get('quantity', 1),
            'price': offer.get('price'),
            'status': 'declined',
            'timestamp': datetime.now().isoformat()
        }
        
        trade_item = offer.get('trade_item') or offer.get('shape')
        if trade_item:
            declined_trade['trade_item'] = trade_item
            if offer.get('item_type', 'shape') == 'shape':
                declined_trade['shape'] = trade_item
        
        session['completed_trades'].append(declined_trade)
        
        # Remove from pending offers
        pending_offers.pop(offer_index)
        offer['status'] = 'declined'
    
    # Update session
    session['pending_offers'] = pending_offers
    session['participants'] = participants
    self.sessions[session_key] = session
    
    # Broadcast update
    broadcast_participant_update(
        session_id=self.session_id,
        participants=participants,
        session_info=session,
        update_type='trade_update'
    )
    
    return {
        'success': True,
        'action': action,
        'response': response_type
    }


def _execute_produce_shape_shapefactory(
    self: AgentContextProtocol,
    action: Dict[str, Any],
    participant: Dict[str, Any],
    session: Dict[str, Any],
    session_key: str
) -> Dict[str, Any]:
    """Execute produce_shape action for ShapeFactory"""
    shape = action.get('shape')
    quantity = action.get('quantity', 1)
    
    if not shape:
        return {
            'success': False,
            'action': action,
            'error': 'Missing shape'
        }
    
    try:
        quantity = int(quantity)
        if quantity <= 0:
            return {
                'success': False,
                'action': action,
                'error': 'Quantity must be positive'
            }
    except (ValueError, TypeError):
        return {
            'success': False,
            'action': action,
            'error': f'Invalid quantity: {quantity}'
        }
    
    # Execute production for each shape
    results = []
    for _ in range(quantity):
        result = start_production(participant, session, shape)
        if not result.get('success'):
            return {
                'success': False,
                'action': action,
                'error': result.get('error', 'Production failed'),
                'partial_results': results
            }
        results.append(result)
    
    # Update participant in session
    participants = session.get('participants', [])
    for i, p in enumerate(participants):
        if p.get('id') == self.participant_id:
            participants[i] = participant
            break
    
    session['participants'] = participants
    self.sessions[session_key] = session
    
    # Recompute interface
    from routes.participant import update_participant_experiment_params
    update_participant_experiment_params(participant, session)
    
    # Broadcast update
    broadcast_participant_update(
        session_id=self.session_id,
        participants=participants,
        session_info=session,
        update_type='partial'
    )
    
    return {
        'success': True,
        'action': action,
        'results': results
    }


def _execute_fulfill_order_shapefactory(
    self: AgentContextProtocol,
    action: Dict[str, Any],
    participant: Dict[str, Any],
    session: Dict[str, Any],
    session_key: str
) -> Dict[str, Any]:
    """Execute fulfill_order action for ShapeFactory"""
    order_indices = action.get('order_indices')
    
    if not order_indices:
        return {
            'success': False,
            'action': action,
            'error': 'Missing order_indices'
        }
    
    if not isinstance(order_indices, list):
        return {
            'success': False,
            'action': action,
            'error': 'order_indices must be a list'
        }
    
    exp_params = participant.get('experiment_params', {})
    inventory = exp_params.get('inventory', [])
    tasks = exp_params.get('tasks', [])
    
    if not isinstance(inventory, list):
        inventory = []
    if not isinstance(tasks, list):
        tasks = []
    
    # Validate indices
    for idx in order_indices:
        try:
            idx = int(idx)
            if idx < 0 or idx >= len(tasks):
                return {
                    'success': False,
                    'action': action,
                    'error': f'Invalid order index: {idx}'
                }
        except (ValueError, TypeError):
            return {
                'success': False,
                'action': action,
                'error': f'Invalid order index: {idx}'
            }
    
    # Get shapes to fulfill
    shapes_to_fulfill = [tasks[idx] for idx in order_indices]
    
    # Check if participant has all required shapes
    inventory_copy = inventory.copy()
    for shape in shapes_to_fulfill:
        if shape not in inventory_copy:
            return {
                'success': False,
                'action': action,
                'error': f'Shape {shape} not in inventory'
            }
        inventory_copy.remove(shape)
    
    # Get incentive money
    incentive_money = get_value_from_session_params(session, 'Session.Params.incentiveMoney')
    incentive_money = int(incentive_money) if incentive_money is not None else 60
    
    # Remove shapes from inventory
    for shape in shapes_to_fulfill:
        inventory.remove(shape)
    
    # Remove fulfilled orders from tasks
    # Remove in reverse order to maintain indices
    for idx in sorted(order_indices, reverse=True):
        if idx < len(tasks):
            tasks.pop(idx)
    
    # Add incentive money
    current_money = exp_params.get('money', 0)
    exp_params['money'] = current_money + (incentive_money * len(shapes_to_fulfill))
    
    # Update order progress
    current_order_progress = exp_params.get('order_progress', 0)
    exp_params['order_progress'] = current_order_progress + len(shapes_to_fulfill)
    
    # Update participant
    exp_params['inventory'] = inventory
    exp_params['tasks'] = tasks
    participant['experiment_params'] = exp_params
    
    # Update participant in session
    participants = session.get('participants', [])
    for i, p in enumerate(participants):
        if p.get('id') == self.participant_id:
            participants[i] = participant
            break
    
    session['participants'] = participants
    self.sessions[session_key] = session
    
    # Recompute interface
    from routes.participant import update_participant_experiment_params
    update_participant_experiment_params(participant, session)
    
    # Broadcast update
    broadcast_participant_update(
        session_id=self.session_id,
        participants=participants,
        session_info=session,
        update_type='partial'
    )
    
    return {
        'success': True,
        'action': action,
        'fulfilled_count': len(shapes_to_fulfill),
        'incentive_money': incentive_money * len(shapes_to_fulfill)
    }


# ============================================================================
# DayTrader-specific action handlers
# ============================================================================

def _execute_make_investment_daytrader(
    self: AgentContextProtocol,
    action: Dict[str, Any],
    participant: Dict[str, Any],
    session: Dict[str, Any],
    session_key: str
) -> Dict[str, Any]:
    """Execute make_investment action for DayTrader"""
    invest_price = action.get('invest_price')
    invest_decision_type = action.get('invest_decision_type')  # 'individual' or 'group'
    
    if invest_price is None:
        return {
            'success': False,
            'action': action,
            'error': 'Missing invest_price'
        }
    
    try:
        invest_price = float(invest_price)
    except (ValueError, TypeError):
        return {
            'success': False,
            'action': action,
            'error': f'Invalid invest_price: {invest_price}'
        }
    
    if invest_decision_type not in ['individual', 'group']:
        return {
            'success': False,
            'action': action,
            'error': f'Invalid invest_decision_type: {invest_decision_type}'
        }
    
    # Validate price range
    min_price = get_value_from_session_params(session, 'Session.Params.minTradePrice')
    max_price = get_value_from_session_params(session, 'Session.Params.maxTradePrice')
    min_price = float(min_price) if min_price is not None else 15.0
    max_price = float(max_price) if max_price is not None else 100.0
    
    if invest_price < min_price or invest_price > max_price:
        return {
            'success': False,
            'action': action,
            'error': f'Investment price must be between ${min_price} and ${max_price}'
        }
    
    # Check if participant has enough money
    exp_params = participant.get('experiment_params', {})
    current_money = exp_params.get('money', 0)
    
    if current_money < invest_price:
        return {
            'success': False,
            'action': action,
            'error': f'Insufficient funds. Need ${invest_price}, have ${current_money}'
        }
    
    # Store investment - use investment_history (consistent with submit_investment)
    # Initialize investment_history if it doesn't exist
    if 'investment_history' not in exp_params:
        exp_params['investment_history'] = []
    
    # Ensure investment_history is a list
    if not isinstance(exp_params['investment_history'], list):
        exp_params['investment_history'] = []
    
    # Create investment record (consistent with submit_investment format)
    investment_record = {
        'id': str(uuid.uuid4()),
        'investment_amount': invest_price,
        'investment_type': invest_decision_type,
        'timestamp': datetime.now().isoformat(),
        'money_before': current_money,
        'money_after': current_money - invest_price
    }
    
    # Add to investment history
    exp_params['investment_history'].append(investment_record)
    
    # Deduct money
    exp_params['money'] = current_money - invest_price
    
    participant['experiment_params'] = exp_params
    
    # Update participant in session
    participants = session.get('participants', [])
    for i, p in enumerate(participants):
        if p.get('id') == self.participant_id:
            participants[i] = participant
            break
    
    session['participants'] = participants
    self.sessions[session_key] = session
    
    # Recompute interface
    from routes.participant import update_participant_experiment_params
    update_participant_experiment_params(participant, session)
    
    # Broadcast update
    broadcast_participant_update(
        session_id=self.session_id,
        participants=participants,
        session_info=session,
        update_type='partial'
    )
    
    return {
        'success': True,
        'action': action,
        'investment_id': investment_record['id'],
        'investment': investment_record,
        'remaining_money': exp_params['money']
    }


# ============================================================================
# EssayRanking-specific action handlers
# ============================================================================

def _execute_get_essay_content_essayranking(
    self: AgentContextProtocol,
    action: Dict[str, Any],
    participant: Dict[str, Any],
    session: Dict[str, Any],
    session_key: str
) -> Dict[str, Any]:
    """Execute get_essay_content action for EssayRanking - reads PDF content"""
    essay_name = action.get('essay_name')
    essay_id = action.get('essay_id')  # Also support essay_id for backward compatibility
    
    if not essay_name and not essay_id:
        return {
            'success': False,
            'action': action,
            'error': 'Missing essay_name or essay_id'
        }
    
    # Find essay in session by name or id
    essays = session.get('essays', [])
    essay = None
    for e in essays:
        if essay_id and e.get('essay_id') == essay_id:
            essay = e
            break
        elif essay_name:
            # Try to match by title, original_filename, or filename (without extension)
            e_title = e.get('title', '').lower().strip()
            e_original = e.get('original_filename', '').lower().strip()
            e_filename = e.get('filename', '').replace('.pdf', '').lower().strip()
            essay_name_lower = essay_name.lower().strip()
            
            if (e_title == essay_name_lower or 
                e_original == essay_name_lower or 
                e_filename == essay_name_lower or
                e_title == essay_name_lower.replace('.pdf', '') or
                e_original == essay_name_lower.replace('.pdf', '')):
                essay = e
                break
    
    if not essay:
        return {
            'success': False,
            'action': action,
            'error': f'Essay not found: {essay_name or essay_id}. Available essays: {[e.get("title") or e.get("original_filename") for e in essays]}'
        }
    
    # Get essay_id for checking if already read
    found_essay_id = essay.get('essay_id')
    
    # Check if essay has already been read
    read_essays = participant.get('read_essays', {})
    if found_essay_id and found_essay_id in read_essays:
        # Essay already read, return the existing content
        existing_data = read_essays[found_essay_id]
        return {
            'success': True,
            'action': action,
            'essay_id': found_essay_id,
            'essay_name': essay.get('title', ''),
            'content': existing_data.get('content', '')[:5000] + '...' if len(existing_data.get('content', '')) > 5000 else existing_data.get('content', ''),
            'content_length': len(existing_data.get('content', '')),
            'message': f'Essay "{essay.get("title", found_essay_id)}" was already read previously. Content is available in your context.',
            'already_read': True
        }
    
    # Get file path
    filename = essay.get('filename')
    if not filename:
        return {
            'success': False,
            'action': action,
            'error': 'Essay filename not found'
        }
    
    # Read PDF file
    import os
    upload_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'uploads', 'essays')
    file_path = os.path.join(upload_dir, filename)
    
    if not os.path.exists(file_path):
        return {
            'success': False,
            'action': action,
            'error': f'Essay file not found: {filename}'
        }
    
    # Try to read PDF content
    try:
        # Try PyPDF2 first
        try:
            import PyPDF2
            with open(file_path, 'rb') as file:
                pdf_reader = PyPDF2.PdfReader(file)
                content = []
                for page_num, page in enumerate(pdf_reader.pages):
                    text = page.extract_text()
                    if text.strip():
                        content.append(f"--- Page {page_num + 1} ---\n{text}")
                essay_content = '\n\n'.join(content)
        except ImportError:
            # Fallback to pdfplumber
            try:
                import pdfplumber
                with pdfplumber.open(file_path) as pdf:
                    content = []
                    for page_num, page in enumerate(pdf.pages):
                        text = page.extract_text()
                        if text:
                            content.append(f"--- Page {page_num + 1} ---\n{text}")
                    essay_content = '\n\n'.join(content)
            except ImportError:
                # If no PDF library is available, return error
                return {
                    'success': False,
                    'action': action,
                    'error': 'PDF reading library not available. Please install PyPDF2 or pdfplumber.'
                }
    except Exception as e:
        return {
            'success': False,
            'action': action,
            'error': f'Error reading PDF: {str(e)}'
        }
    
    if not essay_content or not essay_content.strip():
        return {
            'success': False,
            'action': action,
            'error': 'Could not extract text from PDF'
        }
    
    # Store essay content in participant's memory/context for future reference
    # This allows the agent to remember what it read
    if 'read_essays' not in participant:
        participant['read_essays'] = {}
    
    # Use found_essay_id (which was set earlier when finding the essay)
    participant['read_essays'][found_essay_id] = {
        'essay_id': found_essay_id,
        'title': essay.get('title', ''),
        'content': essay_content,
        'read_at': datetime.now().isoformat()
    }
    
    # Update participant in session
    participants = session.get('participants', [])
    for i, p in enumerate(participants):
        if p.get('id') == self.participant_id:
            participants[i] = participant
            break
    
    session['participants'] = participants
    self.sessions[session_key] = session
    
    return {
        'success': True,
        'action': action,
        'essay_id': found_essay_id,
        'essay_name': essay.get('title', ''),
        'content': essay_content[:5000] + '...' if len(essay_content) > 5000 else essay_content,  # Truncate for response
        'content_length': len(essay_content),
        'message': f'Successfully read essay "{essay.get("title", found_essay_id)}" ({len(essay_content)} characters). The full content is now available in your context under <READ ESSAYS CONTENT> section.'
    }


def _execute_submit_ranking_essayranking(
    self: AgentContextProtocol,
    action: Dict[str, Any],
    participant: Dict[str, Any],
    session: Dict[str, Any],
    session_key: str
) -> Dict[str, Any]:
    """Execute submit_ranking action for EssayRanking"""
    rankings = action.get('rankings')
    
    if not rankings:
        return {
            'success': False,
            'action': action,
            'error': 'Missing rankings'
        }
    
    if not isinstance(rankings, list):
        return {
            'success': False,
            'action': action,
            'error': 'rankings must be a list'
        }
    
    # Validate rankings
    essay_ids = set()
    ranks = set()
    
    # Get available essays from session
    available_essays = session.get('essays', [])
    available_essay_ids = {e.get('essay_id') for e in available_essays if e.get('essay_id')}
    # Create mapping from essay names to essay_ids
    essay_name_to_id = {}
    for e in available_essays:
        essay_id = e.get('essay_id')
        if essay_id:
            # Map by title, original_filename, and filename
            title = e.get('title', '').lower().strip()
            original = e.get('original_filename', '').lower().strip()
            filename = e.get('filename', '').replace('.pdf', '').lower().strip()
            if title:
                essay_name_to_id[title] = essay_id
            if original:
                essay_name_to_id[original] = essay_id
            if filename:
                essay_name_to_id[filename] = essay_id
    
    for ranking in rankings:
        if not isinstance(ranking, dict):
            return {
                'success': False,
                'action': action,
                'error': 'Each ranking must be a dictionary'
            }
        
        # Support both essay_name and essay_id
        essay_name = ranking.get('essay_name')
        essay_id = ranking.get('essay_id')
        
        # Convert essay_name to essay_id if needed
        if essay_name and not essay_id:
            essay_name_lower = essay_name.lower().strip()
            essay_id = essay_name_to_id.get(essay_name_lower) or essay_name_to_id.get(essay_name_lower.replace('.pdf', ''))
            if not essay_id:
                return {
                    'success': False,
                    'action': action,
                    'error': f'Essay not found by name: {essay_name}. Available essays: {[e.get("title") or e.get("original_filename") for e in available_essays]}'
                }
        
        if not essay_id:
            return {
                'success': False,
                'action': action,
                'error': 'Missing essay_name or essay_id in ranking'
            }
        
        rank = ranking.get('rank')
        
        if rank is None:
            return {
                'success': False,
                'action': action,
                'error': 'Missing rank in ranking'
            }
        
        try:
            rank = int(rank)
        except (ValueError, TypeError):
            return {
                'success': False,
                'action': action,
                'error': f'Invalid rank: {rank}'
            }
        
        # Validate essay_id exists
        if essay_id not in available_essay_ids:
            return {
                'success': False,
                'action': action,
                'error': f'Essay not found: {essay_id}'
            }
        
        if essay_id in essay_ids:
            return {
                'success': False,
                'action': action,
                'error': f'Duplicate essay: {essay_id}'
            }
        
        if rank in ranks:
            return {
                'success': False,
                'action': action,
                'error': f'Duplicate rank: {rank}'
            }
        
        essay_ids.add(essay_id)
        ranks.add(rank)
    
    # Validate that all essays are ranked
    if len(essay_ids) != len(available_essay_ids):
        missing_essay_ids = available_essay_ids - essay_ids
        missing_essays = [e.get('title') or e.get('original_filename') for e in available_essays if e.get('essay_id') in missing_essay_ids]
        return {
            'success': False,
            'action': action,
            'error': f'Missing rankings for essays: {missing_essays}'
        }
    
    # Store rankings (convert essay_name to essay_id if needed, but keep both for reference)
    exp_params = participant.get('experiment_params', {})
    # Normalize rankings to use essay_id, and include essay_title for display
    normalized_rankings = []
    for ranking in rankings:
        normalized_ranking = ranking.copy()
        # If ranking has essay_name but not essay_id, find the essay_id
        if 'essay_name' in normalized_ranking and 'essay_id' not in normalized_ranking:
            essay_name = normalized_ranking.get('essay_name')
            essay_name_lower = essay_name.lower().strip()
            # Find essay_id from available essays
            for e in available_essays:
                e_title = e.get('title', '').lower().strip()
                e_original = e.get('original_filename', '').lower().strip()
                if (e_title == essay_name_lower or 
                    e_original == essay_name_lower or
                    e_title == essay_name_lower.replace('.pdf', '') or
                    e_original == essay_name_lower.replace('.pdf', '')):
                    normalized_ranking['essay_id'] = e.get('essay_id')
                    # Also store essay_title for display
                    normalized_ranking['essay_title'] = e.get('title') or e.get('original_filename') or essay_name
                    break
        # Ensure essay_id is present
        if 'essay_id' not in normalized_ranking:
            # Try to find by essay_id if it was provided directly
            essay_id = ranking.get('essay_id')
            if essay_id:
                normalized_ranking['essay_id'] = essay_id
                # Find essay_title from available essays
                for e in available_essays:
                    if e.get('essay_id') == essay_id:
                        normalized_ranking['essay_title'] = e.get('title') or e.get('original_filename') or essay_id
                        break
        # If essay_id is present but essay_title is missing, find it from available essays
        if 'essay_id' in normalized_ranking and 'essay_title' not in normalized_ranking:
            essay_id = normalized_ranking.get('essay_id')
            for e in available_essays:
                if e.get('essay_id') == essay_id:
                    normalized_ranking['essay_title'] = e.get('title') or e.get('original_filename') or essay_id
                    break
        normalized_rankings.append(normalized_ranking)
    
    exp_params['rankings'] = normalized_rankings
    participant['experiment_params'] = exp_params
    
    # Update participant in session
    participants = session.get('participants', [])
    for i, p in enumerate(participants):
        if p.get('id') == self.participant_id:
            participants[i] = participant
            break
    
    session['participants'] = participants
    self.sessions[session_key] = session
    
    # Recompute interface
    from routes.participant import update_participant_experiment_params
    update_participant_experiment_params(participant, session)
    
    # Broadcast update
    broadcast_participant_update(
        session_id=self.session_id,
        participants=participants,
        session_info=session,
        update_type='partial'
    )
    
    return {
        'success': True,
        'action': action,
        'rankings_count': len(rankings)
    }


# ============================================================================
# HiddenProfile-specific action handlers
# ============================================================================

def _execute_get_candidate_names_hiddenprofile(
    self: AgentContextProtocol,
    action: Dict[str, Any],
    participant: Dict[str, Any],
    session: Dict[str, Any],
    session_key: str
) -> Dict[str, Any]:
    """Execute get_candidate_names action for HiddenProfile - returns list of candidate names"""
    candidate_names = get_value_from_session_params(session, 'Session.Params.candidateNames')
    
    if candidate_names is None:
        return {
            'success': False,
            'action': action,
            'error': 'Candidate names not found in session parameters'
        }
    
    # Handle different formats: list, string (comma-separated), or single value
    if isinstance(candidate_names, list):
        names = candidate_names
    elif isinstance(candidate_names, str):
        if ',' in candidate_names:
            names = [name.strip() for name in candidate_names.split(',') if name.strip()]
        else:
            names = [candidate_names.strip()] if candidate_names.strip() else []
    else:
        names = []
    
    return {
        'success': True,
        'action': action,
        'candidate_names': names,
        'count': len(names)
    }


def _execute_submit_initial_vote_hiddenprofile(
    self: AgentContextProtocol,
    action: Dict[str, Any],
    participant: Dict[str, Any],
    session: Dict[str, Any],
    session_key: str
) -> Dict[str, Any]:
    """Execute submit_initial_vote action for HiddenProfile"""
    candidate_name = action.get('candidate_name')
    
    if not candidate_name:
        return {
            'success': False,
            'action': action,
            'error': 'Missing candidate_name'
        }
    
    # Validate candidate name exists
    candidate_names = get_value_from_session_params(session, 'Session.Params.candidateNames')
    if candidate_names is None:
        return {
            'success': False,
            'action': action,
            'error': 'Candidate names not found in session parameters'
        }
    
    # Handle different formats
    valid_names = []
    if isinstance(candidate_names, list):
        valid_names = candidate_names
    elif isinstance(candidate_names, str):
        if ',' in candidate_names:
            valid_names = [name.strip() for name in candidate_names.split(',') if name.strip()]
        else:
            valid_names = [candidate_names.strip()] if candidate_names.strip() else []
    
    # Check if candidate name is valid (case-insensitive)
    candidate_name_lower = candidate_name.strip().lower()
    valid_candidate = None
    for name in valid_names:
        if name.lower() == candidate_name_lower:
            valid_candidate = name  # Use the original case from the list
            break
    
    if not valid_candidate:
        return {
            'success': False,
            'action': action,
            'error': f'Invalid candidate name: {candidate_name}. Valid candidates: {valid_names}'
        }
    
    # Check if already voted
    exp_params = participant.get('experiment_params', {})
    if exp_params.get('initial_vote') and exp_params.get('initial_vote') != 'none':
        return {
            'success': False,
            'action': action,
            'error': f'Initial vote already submitted: {exp_params.get("initial_vote")}'
        }
    
    # Update participant's initial vote
    exp_params['initial_vote'] = valid_candidate
    participant['experiment_params'] = exp_params
    
    # Update participant in session
    participants = session.get('participants', [])
    for i, p in enumerate(participants):
        if p.get('id') == self.participant_id:
            participants[i] = participant
            break
    
    session['participants'] = participants
    self.sessions[session_key] = session
    
    # Recompute interface
    from routes.participant import update_participant_experiment_params
    update_participant_experiment_params(participant, session)
    
    # Broadcast update
    broadcast_participant_update(
        session_id=self.session_id,
        participants=participants,
        session_info=session,
        update_type='partial'
    )
    
    return {
        'success': True,
        'action': action,
        'candidate_name': valid_candidate,
        'message': f'Successfully submitted initial vote for {valid_candidate}'
    }


def _execute_submit_final_vote_hiddenprofile(
    self: AgentContextProtocol,
    action: Dict[str, Any],
    participant: Dict[str, Any],
    session: Dict[str, Any],
    session_key: str
) -> Dict[str, Any]:
    """Execute submit_final_vote action for HiddenProfile"""
    candidate_name = action.get('candidate_name')
    
    if not candidate_name:
        return {
            'success': False,
            'action': action,
            'error': 'Missing candidate_name'
        }
    
    # Validate candidate name exists
    candidate_names = get_value_from_session_params(session, 'Session.Params.candidateNames')
    if candidate_names is None:
        return {
            'success': False,
            'action': action,
            'error': 'Candidate names not found in session parameters'
        }
    
    # Handle different formats
    valid_names = []
    if isinstance(candidate_names, list):
        valid_names = candidate_names
    elif isinstance(candidate_names, str):
        if ',' in candidate_names:
            valid_names = [name.strip() for name in candidate_names.split(',') if name.strip()]
        else:
            valid_names = [candidate_names.strip()] if candidate_names.strip() else []
    
    # Check if candidate name is valid (case-insensitive)
    candidate_name_lower = candidate_name.strip().lower()
    valid_candidate = None
    for name in valid_names:
        if name.lower() == candidate_name_lower:
            valid_candidate = name  # Use the original case from the list
            break
    
    if not valid_candidate:
        return {
            'success': False,
            'action': action,
            'error': f'Invalid candidate name: {candidate_name}. Valid candidates: {valid_names}'
        }
    
    # Check if already voted
    exp_params = participant.get('experiment_params', {})
    if exp_params.get('final_vote') and exp_params.get('final_vote') != 'none':
        return {
            'success': False,
            'action': action,
            'error': f'Final vote already submitted: {exp_params.get("final_vote")}'
        }
    
    # Update participant's final vote
    exp_params['final_vote'] = valid_candidate
    participant['experiment_params'] = exp_params
    
    # Update participant in session
    participants = session.get('participants', [])
    for i, p in enumerate(participants):
        if p.get('id') == self.participant_id:
            participants[i] = participant
            break
    
    session['participants'] = participants
    self.sessions[session_key] = session
    
    # Recompute interface
    from routes.participant import update_participant_experiment_params
    update_participant_experiment_params(participant, session)
    
    # Broadcast update
    broadcast_participant_update(
        session_id=self.session_id,
        participants=participants,
        session_info=session,
        update_type='partial'
    )
    
    return {
        'success': True,
        'action': action,
        'candidate_name': valid_candidate,
        'message': f'Successfully submitted final vote for {valid_candidate}'
    }


# ============================================================================
# Register action handlers for each experiment type
# ============================================================================

def _register_all_handlers():
    """Register all action handlers for all experiment types"""
    # ShapeFactory handlers
    register_action_handler('shapefactory', 'propose_trade_offer', _execute_propose_trade_offer_shapefactory)
    register_action_handler('shapefactory', 'cancel_trade_offer', _execute_cancel_trade_offer_shapefactory)
    register_action_handler('shapefactory', 'trade_response', _execute_trade_response_shapefactory)
    register_action_handler('shapefactory', 'produce_shape', _execute_produce_shape_shapefactory)
    register_action_handler('shapefactory', 'fulfill_order', _execute_fulfill_order_shapefactory)
    
    # DayTrader handlers
    register_action_handler('daytrader', 'make_investment', _execute_make_investment_daytrader)
    
    # EssayRanking handlers
    register_action_handler('essayranking', 'get_essay_content', _execute_get_essay_content_essayranking)
    register_action_handler('essayranking', 'submit_ranking', _execute_submit_ranking_essayranking)
    
    # HiddenProfile handlers
    register_action_handler('hiddenprofile', 'get_candidate_names', _execute_get_candidate_names_hiddenprofile)
    register_action_handler('hiddenprofile', 'submit_initial_vote', _execute_submit_initial_vote_hiddenprofile)
    register_action_handler('hiddenprofile', 'submit_final_vote', _execute_submit_final_vote_hiddenprofile)
    
    # WordGuessing handlers (only message, which is already handled as common action)


# Initialize handlers on module import
_register_all_handlers()
